import type { ConditionPage } from '../lib/content-types';

export const conditions: ConditionPage[] = [
  {
    slug: 'infertility-problems',
    path: '/infertility-problems/',
    group: 'infertility',
    title: 'Infertility Problems',
    lede: 'Understanding the Challenge. Finding the Right Path Forward.',
    metaTitle: 'Infertility Treatment in Mumbai, India | Wonder IVF',
    metaDescription:
      'Explore infertility treatment in Mumbai, Maharashtra at Wonder IVF with personalised fertility solutions and experienced specialist support.',
    image: '/images/conditions/fertility-support-consultation-india.webp',
    imageAlt: 'Fertility support consultation for couples seeking treatment in India',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'According to the WHO, infertility affects approximately one in six people globally during their reproductive years — nearly 17.5% of the adult population worldwide.',
          'In India, approximately 10 to 15% of married couples face infertility challenges, corresponding to nearly 27.5 million couples, and the country accounts for nearly 25% of the global infertility burden.',
          'Understanding infertility problems is the first step toward finding the right solution. Advances in IVF and assisted reproduction have helped many couples move closer to parenthood.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Are Infertility Problems?',
        paragraphs: [
          'Infertility refers to the inability to conceive after 12 months of regular, unprotected intercourse (or 6 months for women over 35). It can result from issues in either partner or a combination of factors.',
          'With an accurate diagnosis and a personalised treatment plan, your fertility specialist can help identify the most suitable path forward.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/infertility-treatment-in-mumbai-india.webp',
        alt: 'Infertility treatment at Wonder IVF in Mumbai, India for couples seeking parenthood',
      },
      {
        type: 'cards',
        heading: 'Types of Infertility',
        cards: [
          { title: 'Primary Infertility', text: 'When a couple has never been able to conceive.' },
          { title: 'Secondary Infertility', text: 'Difficulty conceiving after a previous pregnancy.' },
        ],
      },
      {
        type: 'prose',
        heading: 'Common Causes of Infertility Problems',
        paragraphs: ['Infertility can arise due to a variety of reasons affecting both partners.'],
      },
      {
        type: 'list',
        heading: 'Female Factors',
        items: [
          'Ovulation disorders (PCOS/PMOS)',
          'Blocked fallopian tubes',
          'Endometriosis',
          'Hormonal imbalances',
          'Age-related decline in fertility',
          'Premature ovarian failure',
          'Sexual disorders',
        ],
      },
      {
        type: 'list',
        heading: 'Male Factors',
        items: [
          'Low or zero sperm count',
          'Poor sperm motility or morphology',
          'Hormonal issues',
          'Genetic conditions',
          'Sexual disorders',
        ],
      },
      {
        type: 'prose',
        heading: 'Combined or Unexplained Factors',
        paragraphs: [
          'In some cases, infertility may involve both partners, or it may remain unexplained even after evaluation.',
          'Understanding these causes helps guide the most effective solutions.',
        ],
      },
      {
        type: 'list',
        heading: 'Symptoms of Infertility',
        intro: 'Infertility often does not present clear symptoms, but some indicators may include:',
        items: [
          'Irregular menstrual cycles',
          'Painful periods',
          'Sexual problems',
          'Excessive hair growth on the face in women',
        ],
        note: 'Early diagnosis can play an important role in planning effective treatment.',
      },
      {
        type: 'list',
        heading: 'When Should You See a Fertility Specialist?',
        items: [
          'If you have been trying to conceive for over a year',
          'If the woman is over 35 and has been trying for 6 months',
          'If there are known reproductive or hormonal issues',
          'If there is a history of miscarriages',
        ],
        note: 'Consulting early at a trusted fertility clinic can help avoid unnecessary delays in evaluation and treatment.',
      },
      {
        type: 'list',
        heading: 'How Are Infertility Problems Diagnosed?',
        intro: 'A comprehensive evaluation may include:',
        items: [
          'Medical history and lifestyle assessment',
          'Hormonal testing',
          'Ultrasound and imaging',
          'Semen analysis',
          'Advanced diagnostic procedures, if required',
        ],
        note: 'This helps identify the underlying cause and shape a personalised treatment plan.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Infertility',
        intro: 'Treatment depends on the underlying cause and may include:',
        items: [
          'Lifestyle changes and medical management',
          'Ovulation induction',
          'IUI (Intrauterine Insemination)',
          'IVF (In Vitro Fertilization)',
          'ICSI (Intracytoplasmic Sperm Injection)',
          'Advanced reproductive techniques',
        ],
        note: 'Your fertility specialist can advise which of these options is most suitable for your diagnosis.',
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF?',
        items: [
          'Expertise in male and female infertility',
          'Advanced diagnostics and treatment',
          'Customised fertility plans',
          'Ethical and transparent approach',
          'Care aligned with standards practised at leading IVF clinics worldwide',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Infertility can feel overwhelming, but the right support can make a difference. With advanced fertility treatment and IVF available in India, many couples are able to move forward with greater clarity. Wonder IVF is here to guide you at every step — with clarity, care, and the right treatment approach.',
      },
    ],
  },
  {
    slug: 'male-factor-infertility',
    path: '/male-factor-infertility/',
    group: 'male',
    title: 'Male Factor Infertility',
    lede: 'Understanding the Cause. Improving the Outcome.',
    metaTitle:
      'Male Infertility Treatment in Mumbai, Maharashtra | Male Fertility Clinic in India',
    metaDescription:
      'Get expert male infertility treatment in Mumbai at a trusted male fertility clinic in Maharashtra, offering personalised diagnosis and advanced care.',
    image: '/images/conditions/male-fertility-evaluation-mumbai.webp',
    imageAlt: 'Male fertility evaluation and reproductive health assessment at Wonder IVF Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Male fertility plays an equally important role in conception. Male factor infertility contributes to nearly half of all infertility cases, yet it is often under-discussed.',
          'With the right diagnosis and targeted treatment, many men can address fertility challenges. Care focuses on identifying the exact issue so that the most appropriate options can be offered.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Male Factor Infertility?',
        paragraphs: [
          'Male factor infertility refers to any condition that affects sperm production, quality, or delivery. It can involve issues with sperm count, motility (movement), morphology (shape), the complete absence of sperm, or sexual problems such as ejaculatory disorders.',
          'Male fertility is evaluated using advanced diagnostic techniques to support accurate assessment and personalised care.',
        ],
      },
      {
        type: 'cards',
        heading: 'Common Types of Male Factor Infertility',
        cards: [
          {
            title: 'Azoospermia',
            text: 'A condition where no sperm is present in the ejaculate. It may be due to blockage (obstructive) or impaired sperm production (non-obstructive).',
          },
          {
            title: 'Oligozoospermia',
            text: 'Low sperm count, which reduces the chances of fertilization.',
          },
          {
            title: 'Asthenozoospermia',
            text: 'Poor sperm motility, meaning sperm cannot swim effectively toward the egg.',
          },
          {
            title: 'Teratozoospermia',
            text: 'Abnormal sperm shape, which may affect fertilization.',
          },
          {
            title: 'Oligoasthenoteratozoospermia (OAT)',
            text: 'A combination of low count, poor motility, and abnormal morphology — one of the more complex forms of male infertility.',
          },
        ],
      },
      {
        type: 'list',
        heading: 'Causes of Male Infertility',
        intro: 'Male infertility can occur due to a variety of factors, including:',
        items: [
          'Lifestyle factors (smoking, alcohol, stress)',
          'Hormonal imbalances',
          'Genetic conditions',
          'Varicocele (enlarged veins in the scrotum)',
          'Infections affecting reproductive organs',
          'Exposure to toxins or heat',
          'Previous surgeries or injuries',
        ],
        note: 'Understanding the specific cause or causes helps guide effective treatment.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Male Infertility',
        intro: 'In many cases there are no obvious symptoms apart from difficulty in conceiving. However, some signs may include:',
        items: [
          'Low libido',
          'Pain or swelling in the testicular area',
          'Ejaculation problems',
          'Reduced facial or body hair (a hormonal indication)',
        ],
        note: 'Early evaluation allows treatment to begin sooner.',
      },
      {
        type: 'list',
        heading: 'How Is Male Infertility Diagnosed?',
        intro: 'A comprehensive diagnostic approach may include:',
        items: [
          'Semen analysis — evaluates parameters such as count, motility, and morphology',
          'Sperm DNA fragmentation test — assesses genetic integrity',
          'Hormonal testing — checks testosterone and other hormone levels',
          'Ultrasound — identifies structural issues such as varicocele',
          'Advanced diagnostic tests such as karyotype and Yq micro deletion, if required',
        ],
        note: 'This supports an accurate diagnosis in line with established fertility treatment protocols.',
      },
      {
        type: 'image',
        src: '/images/conditions/male-fertility-consultation-mumbai.webp',
        alt: 'Male fertility consultation with IVF specialist at Wonder IVF Mumbai',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Male Factor Infertility',
        intro: 'Treatment is personalised based on the condition and may include:',
        items: [
          'Lifestyle modification and medical management',
          'Hormonal therapy, if required',
          'Sperm retrieval techniques (TESA/PESA/MicroTESE)',
          'ICSI (Intracytoplasmic Sperm Injection) for precise fertilization',
          'Advanced sperm selection techniques',
          'Testicular rejuvenation',
        ],
        note: 'These approaches can improve the chances of successful treatment.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Diagnosis and Treatment',
        items: [
          'Improves the chances of fertilization',
          'May support IVF outcomes',
          'Identifies the correct treatment pathway',
          'Reduces delays and repeated failures',
          'Provides clarity and confidence',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Male Infertility Treatment?',
        items: [
          'Advanced diagnostic and lab support',
          'Expertise in complex male infertility cases',
          'Customised treatment strategies',
          'Ethical and transparent approach',
          'Care guided by modern fertility protocols and standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Male infertility is often treatable, and with the right approach parenthood may be possible. Wonder IVF guides you with clarity, care, and advanced solutions as you take confident steps through your fertility journey.',
      },
    ],
  },
  {
    slug: 'female-factor-infertility',
    path: '/female-factor-infertility/',
    group: 'female',
    title: 'Female Factor Infertility',
    lede: 'Understanding Your Body. Supporting Your Journey.',
    metaTitle: 'Female Infertility Treatment in Mumbai | Gynaecologist for Female Infertility',
    metaDescription:
      'Get female infertility treatment in Mumbai with expert guidance from a gynaecologist for female infertility and personalised fertility care.',
    image: '/images/conditions/female-fertility-treatment-india.webp',
    imageAlt: 'Female fertility treatment and advanced reproductive care services in India',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Female fertility is a crucial part of the journey to parenthood. Female factor infertility contributes to a large share of infertility cases, making timely awareness and diagnosis essential.',
          'Care focuses on identifying the root cause of female infertility and offering personalised options that are suited to your diagnosis.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Female Factor Infertility?',
        paragraphs: [
          'Female factor infertility refers to conditions that affect a woman’s ability to conceive or sustain a pregnancy. These may involve issues related to ovulation, egg quality, fallopian tubes, uterus, or hormonal balance.',
          'Evaluation follows established protocols so that diagnosis is accurate and treatment plans are tailored to each patient.',
        ],
      },
      {
        type: 'cards',
        heading: 'Common Types of Female Factor Infertility',
        cards: [
          {
            title: 'Ovulatory Disorders (PMOS & Hormonal Issues)',
            text: 'Irregular ovulation or absence of ovulation is one of the most common causes of infertility in women.',
          },
          {
            title: 'Fallopian Tube Disorders',
            text: 'Damage or blockage in the fallopian tubes can prevent fertilization.',
          },
          {
            title: 'Endometriosis',
            text: 'A condition where uterine tissue grows outside the uterus, affecting fertility.',
          },
          {
            title: 'Uterine Conditions (Fibroids, Polyps, Adenomyosis)',
            text: 'Structural abnormalities may interfere with implantation.',
          },
          {
            title: 'Low Ovarian Reserve (Diminished Ovarian Reserve)',
            text: 'Reduced egg quality or quantity, often associated with age.',
          },
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/female-infertility-treatment-in-mumbai.webp',
        alt: 'Female infertility treatment at Wonder IVF Mumbai with personalized fertility solutions',
      },
      {
        type: 'list',
        heading: 'Causes of Female Infertility',
        intro: 'Female infertility may be caused by a combination of medical and lifestyle factors, including:',
        items: [
          'Hormonal imbalance',
          'PCOS (Polycystic Ovary Syndrome)',
          'Thyroid disorders',
          'Endometriosis',
          'Age-related fertility decline',
          'Stress, smoking, and lifestyle habits',
          'Pelvic infections or surgeries',
          'Genetic conditions',
        ],
        note: 'Understanding these causes allows the most effective solutions to be selected.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Female Infertility',
        intro: 'Many women may not notice symptoms until they try to conceive. However, possible signs include:',
        items: [
          'Irregular or missed periods',
          'Painful menstrual cycles',
          'Hormonal imbalances (weight gain, acne)',
          'Pain during intercourse',
          'Recurrent miscarriages',
        ],
        note: 'Early fertility evaluation can inform treatment planning and improve outcomes.',
      },
      {
        type: 'list',
        heading: 'How Is Female Infertility Diagnosed?',
        intro: 'Advanced diagnostic methods may include:',
        items: [
          'Ovulation tracking and monitoring',
          'Hormonal blood tests',
          'Pelvic ultrasound scans',
          'HSG test for fallopian tubes',
          'Advanced fertility testing when required',
        ],
        note: 'This ensures a clear understanding of your condition and the most suitable treatment approach.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Female Factor Infertility',
        intro: 'Treatment depends on the specific diagnosis and may include:',
        items: [
          'Ovulation induction and cycle regulation',
          'Hormonal therapy',
          'Minimally invasive procedures (laparoscopy/hysteroscopy)',
          'IVF (In Vitro Fertilization)',
          'ICSI (Intracytoplasmic Sperm Injection)',
          'Advanced embryo selection techniques',
        ],
        note: 'Your fertility specialist can advise which options are best suited to your diagnosis and goals.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Diagnosis and Treatment',
        items: [
          'Higher chances of successful conception',
          'Improved IVF outcomes',
          'Faster and more accurate treatment planning',
          'Reduced emotional and financial stress',
          'Better overall reproductive health outcomes',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Female Infertility Treatment?',
        items: [
          'Advanced fertility diagnostics',
          'Experienced IVF specialists',
          'Personalised treatment plans',
          'Ethical and transparent processes',
          'Care aligned with leading fertility care standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Female infertility is often treatable, and with the right support your journey to parenthood can move forward with clarity and hope. Wonder IVF guides you with expertise, care, and advanced solutions, helping you take confident steps toward building your family.',
      },
    ],
  },
  {
    slug: 'unexplained-infertility',
    path: '/unexplained-infertility/',
    group: 'infertility',
    title: 'Unexplained Infertility',
    lede: 'When Tests Are Normal, But Conception Still Feels Out of Reach',
    metaTitle:
      'Unexplained Infertility treatment in Mumbai, Maharashtra | unexplained infertility specialist',
    metaDescription:
      'Find unexplained infertility treatment in Mumbai with an experienced unexplained infertility specialist offering personalised evaluation and fertility care.',
    image: '/images/conditions/unexplained-infertility-treatment-mumbai.webp',
    imageAlt: 'Unexplained infertility treatment and advanced fertility care at Wonder IVF Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'It can be frustrating when all reports appear normal, yet pregnancy does not happen. This situation is known as unexplained infertility — standard tests do not reveal a clear cause, but conception remains challenging.',
          'With the right approach, many couples with unexplained infertility are able to achieve a successful outcome. Care focuses on identifying subtle factors and guiding you toward effective solutions.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Unexplained Infertility?',
        paragraphs: [
          'Unexplained infertility is diagnosed when both partners have normal fertility test results — such as ovulation, sperm quality, and tubal function — but pregnancy does not occur after a reasonable period of trying.',
          'Evaluation can go beyond basic testing to explore underlying factors that may not be immediately visible.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/infertility-care-for-couples-mumbai.webp',
        alt: 'Couple fertility consultation with experienced specialists at Wonder IVF India',
      },
      {
        type: 'list',
        heading: 'Possible Reasons Behind Unexplained Infertility',
        intro: 'Even when tests are normal, certain hidden factors may affect fertility:',
        items: [
          'Subtle egg or sperm quality issues',
          'Minor hormonal imbalances',
          'Implantation-related challenges',
          'Immune or inflammatory factors',
          'Timing-related issues in ovulation or fertilization',
        ],
        note: 'Understanding these possibilities helps guide effective treatment.',
      },
      {
        type: 'list',
        heading: 'When Is It Diagnosed?',
        intro: 'Unexplained infertility is usually considered when:',
        items: [
          'A couple has been trying to conceive for 12 months (or 6 months if over 35)',
          'Ovulation is regular',
          'Fallopian tubes are open',
          'Semen analysis is normal',
        ],
        note: 'In such cases, further evaluation and advanced treatment planning become important.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Unexplained Infertility',
        intro: 'Care focuses on improving the chances of conception through a step-by-step, personalised approach:',
        items: [
          'Ovulation induction with timed intercourse',
          'IUI (Intrauterine Insemination) to enhance fertilization chances',
          'IVF treatment for greater control over fertilization and embryo development',
          'ICSI (Intracytoplasmic Sperm Injection) in selected cases',
          'Advanced embryo selection techniques',
        ],
        note: 'Each treatment is carefully planned based on your individual condition.',
      },
      {
        type: 'list',
        heading: 'Why IVF Is Effective in Unexplained Infertility',
        intro: 'IVF can help overcome unknown barriers by:',
        items: [
          'Ensuring fertilization occurs in a controlled environment',
          'Monitoring embryo development closely',
          'Selecting the most suitable embryos for transfer',
          'Optimizing timing and implantation conditions',
        ],
        note: 'This makes IVF a widely used option for unexplained infertility.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Intervention',
        items: [
          'Increases the chances of conception',
          'Reduces uncertainty and waiting time',
          'Improves treatment planning',
          'Provides better control over the process',
          'Offers clarity and direction in your journey',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Unexplained Infertility?',
        items: [
          'Detailed and advanced fertility evaluation',
          'Customised treatment planning',
          'Use of modern IVF techniques',
          'Clear communication and guidance',
          'Care aligned with leading fertility care standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Clarity',
        text: 'Not having a clear diagnosis does not mean there is no solution. Wonder IVF helps you move beyond uncertainty with the right strategy, care, and expertise, so your treatment journey stays guided and considered.',
      },
    ],
  },
  {
    slug: 'low-ovarian-reserve',
    path: '/low-ovarian-reserve/',
    group: 'infertility',
    title: 'Low Ovarian Reserve',
    lede: 'Understanding Your Fertility Potential, Planning the Right Path',
    metaTitle: 'Low Ovarian Reserve Treatment in Mumbai, Maharashtra | Low AMH Treatment',
    metaDescription:
      'Explore low ovarian reserve treatment in Mumbai, Maharashtra and personalised low AMH treatment with expert fertility guidance and advanced care.',
    image: '/images/conditions/ovarian-reserve-consultation-mumbai.webp',
    imageAlt: 'Ovarian reserve consultation and fertility assessment in Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Ovarian reserve plays a crucial role in a woman’s fertility. Low ovarian reserve means a reduced number or quality of eggs in the ovaries, which can affect the chances of natural conception.',
          'With the right diagnosis and timely care, effective options are available. Treatment focuses on personalised strategies to help improve outcomes and guide you toward the most suitable solution.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Low Ovarian Reserve?',
        paragraphs: [
          'Ovarian reserve refers to the number of follicles present in the ovaries. An ovarian follicle is a small, fluid-filled sac located inside the ovaries. Each follicle houses a single immature egg (oocyte) and provides the necessary nutrients, hormones, and protective environment for it to grow and mature.',
          'A low ovarian reserve indicates that the follicle count is lower than expected for a woman’s age, which may impact fertility potential. The condition is carefully evaluated using advanced diagnostic methods.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/low-ovarian-reserve-treatment-in-mumbai-maharashtra.webp',
        alt: 'Low ovarian reserve treatment at Wonder IVF in Mumbai, Maharashtra, India using advanced fertility solutions',
      },
      {
        type: 'list',
        heading: 'Causes of Low Ovarian Reserve',
        intro: 'Low ovarian reserve can occur due to several factors, including:',
        items: [
          'Increasing age (especially after 35 years)',
          'Genetic factors',
          'Previous ovarian surgeries',
          'Medical treatments such as chemotherapy or radiation',
          'Lifestyle and environmental factors',
        ],
        note: 'Understanding the cause helps in planning the right treatment approach.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Low Ovarian Reserve',
        intro: 'In many cases there may be no clear symptoms. However, some signs may include:',
        items: [
          'Irregular or shorter menstrual cycles',
          'Difficulty in conceiving',
          'Poor response to fertility treatments',
          'A family history of early menopause',
        ],
        note: 'Early diagnosis is key to planning care and understanding your options.',
      },
      {
        type: 'list',
        heading: 'How Is Low Ovarian Reserve Diagnosed?',
        intro: 'A combination of tests may be used to accurately assess ovarian reserve:',
        items: [
          'AMH test (Anti-Müllerian Hormone) — measures egg reserve',
          'FSH levels — indicates ovarian function',
          'Ultrasound (AFC — Antral Follicle Count) — assesses visible follicles in the ovaries',
        ],
        note: 'These tests help design a personalised treatment plan aligned with established fertility protocols.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Low Ovarian Reserve',
        intro: 'While low ovarian reserve cannot be reversed, effective treatment options can improve the chances of conception. Options include:',
        items: [
          'Customised IVF protocols tailored to your response',
          'Advanced stimulation techniques to optimize egg retrieval',
          'ICSI (Intracytoplasmic Sperm Injection) for better fertilization',
          'Embryo freezing for future planning',
          'Donor egg options in selected cases',
        ],
        note: 'The aim is that each patient receives a strategy best suited to their condition.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Diagnosis and Treatment',
        items: [
          'Better planning and timely intervention',
          'Improved IVF outcomes',
          'More control over fertility decisions',
          'Reduced emotional and financial stress',
          'Access to multiple treatment options',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Low Ovarian Reserve Treatment?',
        items: [
          'Advanced diagnostic tools',
          'Individualised treatment plans',
          'Expertise in handling complex fertility cases',
          'Ethical and transparent approach',
          'Care integrated with international standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Low ovarian reserve can feel challenging — but with the right guidance, there are still possibilities. Wonder IVF helps you understand your options and take the next step with clarity and care, so your fertility journey stays thoughtful and supported.',
      },
    ],
  },
  {
    slug: 'pcos-pmos',
    path: '/pcos-pmos/',
    group: 'female',
    title: 'PCOS / PMOS',
    lede: 'Balancing Hormones. Restoring Fertility Naturally & Medically',
    metaTitle: 'PCOS Treatment in Mumbai, India | Expert Fertility Care',
    metaDescription:
      'Explore personalised PCOS treatment in Mumbai, India with expert care, accurate evaluation and fertility-focused support for your reproductive health.',
    image: '/images/conditions/pcos-treatment-in-mumbai-india.webp',
    imageAlt: 'PCOS treatment at Wonder IVF Mumbai, India providing personalized fertility and reproductive care',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'PCOS is one of the most common causes of female infertility today. It affects hormonal balance, ovulation, and overall reproductive health, making conception more challenging.',
          'With the right diagnosis and personalised care, PCOS can be effectively managed. Treatment focuses on restoring balance and supporting your chances of a successful pregnancy.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is PCOS / PMOS?',
        paragraphs: [
          'The name refers to “ovarian cysts”, but those cysts are usually normal, tiny fluid-filled pockets (follicles) holding immature eggs that were not released.',
          'PCOS/PMOS is not an ovarian disease; it is a whole-body hormonal and metabolic imbalance that can have a significant impact on ovulation and fertility.',
        ],
      },
      {
        type: 'list',
        heading: 'Causes of PCOS / PMOS',
        intro: 'PCOD can be influenced by multiple factors, including:',
        items: [
          'Hormonal imbalance (especially androgens)',
          'Insulin resistance',
          'Genetic predisposition',
          'Lifestyle factors such as diet and physical activity',
          'Stress and metabolic conditions',
        ],
        note: 'Understanding these causes helps in designing an effective treatment plan.',
      },
      {
        type: 'list',
        heading: 'Symptoms of PCOS / PMOS',
        intro: 'Symptoms may vary from person to person, but commonly include:',
        items: [
          'Irregular or missed periods',
          'Delayed or absent ovulation',
          'Weight gain or difficulty losing weight',
          'Acne and excessive hair growth',
          'Difficulty in conceiving',
        ],
        note: 'Early identification is important for better outcomes.',
      },
      {
        type: 'list',
        heading: 'How Is PCOS Diagnosed?',
        intro: 'PCOS is diagnosed using a combination of:',
        items: [
          'Hormonal tests (LH, FSH, AMH, insulin levels)',
          'Ultrasound (USG) to assess ovarian structure',
          'Clinical evaluation of symptoms',
        ],
        note: 'This detailed approach supports an accurate diagnosis.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for PCOS',
        intro: 'PCOS is manageable with the right combination of lifestyle changes and medical support. Options include:',
        items: [
          'Lifestyle modification guidance (diet, exercise, weight management)',
          'Medications to regulate hormones and ovulation',
          'Ovulation induction treatments',
          'IUI or IVF for enhanced conception chances',
          'Advanced fertility treatments in complex cases',
        ],
        note: 'Each plan is personalised to suit your body’s response.',
      },
      {
        type: 'list',
        heading: 'Benefits of Managing PCOS Early',
        items: [
          'Improves chances of natural conception',
          'Restores regular ovulation cycles',
          'May support success rates in IVF and IUI',
          'Reduces long-term health risks',
          'Supports overall reproductive health',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for PCOS Treatment?',
        items: [
          'Accurate diagnosis and hormone evaluation',
          'Customised treatment plans',
          'Combining medical and lifestyle approaches',
          'Continuous monitoring and support',
          'Care aligned with advanced fertility treatment standards',
        ],
      },
      {
        type: 'note',
        heading: 'Take Control of Your Fertility',
        text: 'PCOS may feel overwhelming — but with the right care, it is manageable. Wonder IVF guides you with clarity, care, and expertise, helping you move forward with confidence through trusted fertility care.',
      },
    ],
  },
  {
    slug: 'endometriosis',
    path: '/endometriosis/',
    group: 'female',
    title: 'Endometriosis',
    lede: 'Managing Pain, Restoring Fertility, Supporting Your Journey',
    metaTitle: 'Endometriosis Treatment in Mumbai, Maharashtra | Endometriosis Diagnosis Test',
    metaDescription:
      'Explore endometriosis treatment in Mumbai and understand endometriosis diagnosis test options with specialist guidance for timely and personalised care.',
    image: '/images/conditions/endometriosis-treatment-mumbai.webp',
    imageAlt: 'Endometriosis treatment and fertility care services at Wonder IVF Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Endometriosis is a frequently underdiagnosed cause of fertility difficulties and pelvic discomfort — but it does not mean pregnancy is out of reach. Early intervention and specialised care can help you manage these challenges.',
          'Targeted protocols are designed to reduce the impact of endometriosis, protect your ovarian reserve, and support your goals for parenthood.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Endometriosis?',
        paragraphs: [
          'Endometriosis is a condition in which tissue similar to the uterine lining (endometrium) grows outside the uterus — commonly on the ovaries, fallopian tubes, or pelvic lining.',
          'This tissue responds to hormonal changes, leading to inflammation, pain, and sometimes scar tissue formation, which can affect fertility. The condition is diagnosed and managed using established clinical protocols.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/female-reproductive-treatment-mumbai.webp',
        alt: 'Female reproductive treatment and fertility solutions in Mumbai',
      },
      {
        type: 'list',
        heading: 'Causes of Endometriosis',
        intro: 'The exact cause of endometriosis is not fully known, but it may be linked to:',
        items: [
          'Retrograde menstruation (backflow of menstrual blood)',
          'Genetic predisposition',
          'Immune system factors',
          'Chronic inflammation',
        ],
        note: 'Understanding these factors helps guide effective treatment.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Endometriosis',
        intro: 'Symptoms can vary in severity, and some women may have mild or no symptoms. Common signs include:',
        items: [
          'Severe menstrual cramps',
          'Chronic pelvic pain',
          'Pain during or after intercourse',
          'Heavy or irregular periods',
          'Difficulty in conceiving',
        ],
        note: 'Recognising symptoms early can inform timely treatment planning.',
      },
      {
        type: 'list',
        heading: 'How Is Endometriosis Diagnosed?',
        intro: 'A combination of methods may be used to diagnose endometriosis:',
        items: [
          'Ultrasound (USG) for initial evaluation',
          'MRI, if required, for detailed imaging',
          'Laparoscopy for definitive diagnosis and treatment',
          'Clinical assessment of symptoms',
        ],
        note: 'This approach supports an accurate diagnosis.',
      },
      {
        type: 'list',
        heading: 'Impact of Endometriosis on Fertility',
        intro: 'Endometriosis can affect fertility in several ways:',
        items: [
          'Blocking or damaging fallopian tubes',
          'Affecting egg quality and ovulation',
          'Causing inflammation in the pelvic environment',
          'Interfering with embryo implantation',
        ],
        note: 'With proper management, many patients are able to continue with fertility treatment successfully.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Endometriosis',
        intro: 'Treatment is tailored based on severity and fertility goals:',
        items: [
          'Medications to manage pain and hormonal balance',
          'Hormonal therapy to suppress disease progression',
          'Laparoscopic surgery to remove endometriotic tissue',
          'IVF treatment for improved chances of conception',
          'Personalised fertility planning based on your condition',
        ],
        note: 'The goal is to improve both comfort and fertility outcomes.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Management',
        items: [
          'Reduces pain and improves quality of life',
          'Enhances chances of natural conception',
          'May improve IVF and fertility treatment outcomes',
          'Helps prevent progression of the condition',
          'Supports better reproductive health',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Endometriosis Care?',
        items: [
          'Accurate and early diagnosis',
          'Advanced treatment options',
          'Personalised care plans',
          'Ethical and transparent approach',
          'Care aligned with leading fertility treatment standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Endometriosis may feel overwhelming — but with the right care, pregnancy is still possible. Wonder IVF guides you with clarity, care, and expertise as you move forward with confidence.',
      },
    ],
  },
  {
    slug: 'adenomyosis',
    path: '/adenomyosis/',
    group: 'female',
    title: 'Adenomyosis',
    lede: 'Understanding Uterine Health for Better Fertility Outcomes',
    metaTitle: 'Adenomyosis Treatment in Mumbai, India | Adenomyosis Surgery',
    metaDescription:
      'Explore adenomyosis treatment in Mumbai, India and adenomyosis surgery options with specialist-led care tailored to your symptoms and fertility needs.',
    image: '/images/conditions/adenomyosis-treatment-mumbai.webp',
    imageAlt: 'Adenomyosis treatment and fertility management at Wonder IVF Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Uterine health plays a critical role in successful conception and pregnancy. Adenomyosis is a condition that can impact both quality of life and fertility, and it often goes undiagnosed until symptoms become significant.',
          'With timely diagnosis and the right approach, adenomyosis can be effectively managed. Care focuses on improving uterine conditions to support implantation and pregnancy outcomes.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Adenomyosis?',
        paragraphs: [
          'Adenomyosis occurs when the inner lining of the uterus (endometrium) grows into the muscular wall of the uterus. This can cause the uterus to enlarge and affect its normal function.',
          'The condition is evaluated using advanced diagnostic techniques, ensuring accurate assessment and personalised care.',
        ],
      },
      {
        type: 'list',
        heading: 'Causes of Adenomyosis',
        intro: 'The exact cause of adenomyosis is not always clear, but it may be associated with:',
        items: [
          'Previous uterine surgeries (such as dilatation and curettage, C-sections, or fibroid removal)',
          'Chronic inflammation of the uterine lining',
          'Age-related changes, commonly seen in women above 30–35 years',
        ],
        note: 'Understanding these factors helps in planning the right treatment strategy.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Adenomyosis',
        intro: 'Symptoms can vary, and some women may not experience noticeable signs. Common symptoms include:',
        items: [
          'Heavy or prolonged menstrual bleeding',
          'Severe menstrual cramps',
          'Pelvic pain or pressure',
          'Enlarged or tender uterus',
          'Difficulty in conceiving',
        ],
        note: 'Early diagnosis can improve outcomes in IVF and fertility treatment.',
      },
      {
        type: 'list',
        heading: 'How Is Adenomyosis Diagnosed?',
        intro: 'Adenomyosis may be diagnosed through:',
        items: [
          'Ultrasound (USG) for initial evaluation',
          'MRI, if required, for detailed imaging',
          'Clinical assessment of symptoms',
        ],
        note: 'Accurate diagnosis helps in creating a treatment plan aligned with established protocols.',
      },
      {
        type: 'list',
        heading: 'Impact of Adenomyosis on Fertility',
        intro: 'Adenomyosis can affect fertility by:',
        items: [
          'Disrupting implantation',
          'Affecting uterine contractions',
          'Altering the uterine environment',
          'Increasing the risk of miscarriage',
        ],
        note: 'With proper management, many patients are still able to achieve pregnancy through IVF.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Adenomyosis',
        intro: 'Treatment is personalised based on severity and fertility goals:',
        items: [
          'Hormonal therapy to control symptoms and reduce uterine inflammation',
          'Medications to regulate cycles and improve the uterine environment',
          'Surgery to reduce the bulk of disease',
          'Lifestyle and supportive care',
          'IVF treatment for improved chances of conception',
          'Customised embryo transfer strategies',
        ],
        note: 'The approach is planned around your individual condition.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Management',
        items: [
          'Improves chances of successful implantation',
          'Reduces pain and menstrual discomfort',
          'May enhance IVF success rates',
          'Supports a healthier uterine environment',
          'Helps toward better pregnancy outcomes',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Adenomyosis Care?',
        items: [
          'Accurate diagnosis using modern imaging',
          'Personalised treatment strategies',
          'Expertise in handling uterine conditions',
          'Ethical and transparent approach',
          'Care integrated with leading worldwide fertility treatment guidelines',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Adenomyosis can be challenging — but with the right care, a successful pregnancy may be possible. Wonder IVF guides you with clarity, care, and expertise, so your journey stays well-planned and supported.',
      },
    ],
  },
  {
    slug: 'blocked-fallopian-tubes',
    path: '/blocked-fallopian-tubes/',
    group: 'female',
    title: 'Blocked Fallopian Tubes',
    lede: 'Clearing the Path to Conception with the Right Care',
    metaTitle:
      'Blocked Fallopian Tubes Treatment in Mumbai, Maharashtra | Tubal Blockage Treatment',
    metaDescription:
      'Explore blocked fallopian tubes treatment in Mumbai and personalised tubal blockage treatment options with expert diagnosis and fertility-focused care.',
    image: '/images/conditions/fallopian-tube-treatment-mumbai.webp',
    imageAlt: 'Fallopian tube treatment and fertility',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Fallopian tubes play a vital role in natural conception. When these tubes are blocked or damaged, it can prevent the egg and sperm from meeting, making pregnancy difficult.',
          'With accurate diagnosis and the right treatment approach, this condition can be effectively managed. Care focuses on identifying the cause and guiding you toward the most suitable solution.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Are Blocked Fallopian Tubes?',
        paragraphs: [
          'Fallopian tubes connect the ovaries to the uterus and are essential for fertilization. A blockage in one or both tubes can stop the movement of the egg, sperm, or embryo.',
          'Tubal health is evaluated using advanced diagnostic methods, ensuring precise assessment and treatment planning.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/blocked-fallopian-tubes-treatment-mumbai-india.webp',
        alt: 'Blocked fallopian tubes treatment and fertility solutions in Mumbai India',
      },
      {
        type: 'list',
        heading: 'Causes of Blocked Fallopian Tubes',
        intro: 'Blockage can occur due to several reasons, including:',
        items: [
          'Pelvic infections or pelvic inflammatory disease (PID)',
          'Endometriosis',
          'Previous abdominal or pelvic surgeries',
          'Tuberculosis (in some cases)',
          'Scar tissue or adhesions',
          'Hydrosalpinx (fluid-filled tubes)',
        ],
        note: 'Understanding the cause helps determine the right treatment strategy.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Blocked Fallopian Tubes',
        intro: 'In many cases, blocked tubes may not show clear symptoms. However, some signs may include:',
        items: [
          'Difficulty in conceiving',
          'Pelvic pain (especially with infections or endometriosis)',
          'Irregular menstrual patterns in some cases',
          'History of infections or previous surgeries',
        ],
        note: 'Since symptoms may be minimal, proper diagnosis is essential before deciding on treatment.',
      },
      {
        type: 'list',
        heading: 'How Are Blocked Fallopian Tubes Diagnosed?',
        intro: 'A combination of tests may be used to evaluate tubal health:',
        items: [
          'HSG (Hysterosalpingography) — checks for tubal blockage using contrast imaging',
          'Ultrasound (USG) — identifies fluid accumulation or abnormalities',
          'Laparoscopy — provides a detailed view and allows treatment if needed',
        ],
        note: 'This comprehensive approach supports an accurate diagnosis.',
      },
      {
        type: 'list',
        heading: 'Impact on Fertility',
        intro: 'Blocked fallopian tubes can significantly affect natural conception by:',
        items: [
          'Preventing fertilization',
          'Increasing the risk of ectopic pregnancy',
          'Disrupting embryo movement to the uterus',
        ],
        note: 'With proper management, many patients are able to achieve pregnancy through IVF.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Blocked Fallopian Tubes',
        intro: 'Treatment depends on the severity and type of blockage:',
        items: [
          'Tubal surgery to remove minor blockages (in selected cases)',
          'Laparoscopic correction for adhesions or damage',
          'IVF treatment to bypass the fallopian tubes completely',
          'Management of hydrosalpinx before IVF',
        ],
        note: 'IVF is often considered when both tubes are blocked, as it bypasses the tubes entirely.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Diagnosis and Treatment',
        items: [
          'Improves chances of conception',
          'Helps avoid unnecessary delays in treatment',
          'Enables timely decision-making (natural conception vs IVF)',
          'Reduces the risk of complications',
          'Improves overall fertility outcomes',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Tubal Factor Infertility?',
        items: [
          'Advanced diagnostic techniques',
          'Expertise in minimally invasive procedures',
          'Personalised treatment pathways',
          'Ethical and transparent care',
          'Care aligned with leading fertility treatment standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with the Right Solution',
        text: 'Blocked fallopian tubes can be a challenge — but with the right approach, parenthood may still be within reach. Wonder IVF guides you with clarity, care, and expertise as you take confident steps forward.',
      },
    ],
  },
  {
    slug: 'uterine-fibroids',
    path: '/uterine-fibroids/',
    group: 'female',
    title: 'Uterine Fibroids',
    lede: 'Managing Growths, Supporting Fertility, Improving Outcomes',
    metaTitle: 'Uterine Fibroids Treatment in Mumbai, Maharashtra | Fibroids Treatment',
    metaDescription:
      'Explore uterine fibroids treatment in Mumbai, Maharashtra with personalised fibroids treatment options and expert specialist guidance.',
    image: '/images/conditions/fibroids-treatment-mumbai.webp',
    imageAlt: 'Uterine fibroids treatment and fertility care at Wonder IVF Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Uterine fibroids are a common condition that can affect a woman’s reproductive health and fertility. While many fibroids are harmless, some can interfere with conception and pregnancy if they are not properly evaluated.',
          'With accurate diagnosis and personalised care, fibroids can be effectively managed. Care focuses on improving uterine health to support implantation and pregnancy.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Are Uterine Fibroids?',
        paragraphs: [
          'Fibroids are non-cancerous growths that develop in or around the uterus. They can vary in size, number, and location, and may or may not cause symptoms.',
          'Fibroids are assessed carefully using advanced diagnostic methods, ensuring the right treatment approach for each patient.',
        ],
      },
      {
        type: 'cards',
        heading: 'Types of Fibroids',
        intro: 'Fibroids are classified based on their location:',
        cards: [
          {
            title: 'Intramural Fibroids',
            text: 'Located within the muscular wall of the uterus.',
          },
          {
            title: 'Submucosal Fibroids',
            text: 'Grow inside the uterine cavity and may affect implantation.',
          },
          {
            title: 'Subserosal Fibroids',
            text: 'Develop on the outer surface of the uterus.',
          },
        ],
      },
      {
        type: 'prose',
        paragraphs: [
          'The type and position of fibroids play an important role in fertility and treatment planning.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/uterine-fibroids-treatment-in-mumbai-maharashtra.webp',
        alt: 'Uterine fibroids treatment at Wonder IVF in Mumbai, Maharashtra, India with expert fertility specialists',
      },
      {
        type: 'list',
        heading: 'Causes of Fibroids',
        intro: 'The exact cause of fibroids is not fully known, but they are often associated with:',
        items: [
          'Hormonal factors (especially estrogen and progesterone)',
          'Genetic predisposition',
          'Age (more common in women in their 30s and 40s)',
          'Lifestyle and environmental factors',
        ],
        note: 'Understanding these factors helps guide treatment decisions in fertility care and IVF.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Fibroids',
        intro: 'Some women may not experience symptoms, while others may notice:',
        items: [
          'Heavy or prolonged menstrual bleeding',
          'Pelvic pain or pressure',
          'Frequent urination',
          'Pain during intercourse',
          'Difficulty in conceiving',
        ],
        note: 'Early evaluation is important for informed treatment planning.',
      },
      {
        type: 'list',
        heading: 'How Are Fibroids Diagnosed?',
        intro: 'Fibroids may be diagnosed using:',
        items: [
          'Ultrasound (USG) for initial detection',
          'MRI, if required, for detailed assessment',
          'Hysteroscopy or laparoscopy for further evaluation',
        ],
        note: 'This comprehensive approach supports an accurate diagnosis in line with established IVF protocols.',
      },
      {
        type: 'list',
        heading: 'Impact of Fibroids on Fertility',
        intro: 'Fibroids can affect fertility depending on their size and location. They may:',
        items: [
          'Distort the uterine cavity',
          'Interfere with embryo implantation',
          'Block fallopian tubes',
          'Affect blood flow to the uterus',
        ],
        note: 'With proper management, many patients are able to achieve pregnancy.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Fibroids',
        intro: 'Treatment is tailored based on your condition and fertility goals:',
        items: [
          'Monitoring small fibroids that do not affect fertility',
          'Medications to manage symptoms',
          'Hysteroscopic removal for fibroids inside the uterine cavity',
          'Laparoscopic surgery for larger or external fibroids',
          'IVF treatment to improve chances of conception',
        ],
        note: 'The approach is chosen to suit your individual diagnosis.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Management',
        items: [
          'Improves chances of successful implantation',
          'Reduces symptoms and discomfort',
          'May enhance IVF success rates',
          'Helps prevent complications during pregnancy',
          'Supports overall reproductive health',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Fibroid Treatment?',
        items: [
          'Accurate diagnosis and evaluation',
          'Tailored treatment plans',
          'Expertise in minimally invasive procedures',
          'Ethical and transparent approach',
          'Care aligned with leading fertility treatment standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Confidence',
        text: 'Fibroids can be managed — and with the right care, a successful pregnancy may be possible. Wonder IVF guides you with clarity, care, and expertise as you move forward with confidence.',
      },
    ],
  },
  {
    slug: 'premature-ovarian-failure',
    path: '/premature-ovarian-failure/',
    group: 'female',
    title: 'Premature Ovarian Failure',
    lede: 'Early Diagnosis. Personalized Care. Renewed Possibilities',
    metaTitle: 'Premature ovarian failure treatment in Mumbai, India | failure symptoms',
    metaDescription:
      'Learn about premature ovarian failure symptoms and explore personalised premature ovarian failure treatment in Mumbai, India with fertility-focused care.',
    image: '/images/conditions/ovarian-insufficiency-treatment-mumbai.webp',
    imageAlt: 'Ovarian insufficiency treatment and fertility solutions in Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'Being diagnosed with premature ovarian failure can feel unexpected and overwhelming. This condition affects ovarian function at an earlier age, impacting fertility and hormonal balance.',
          'With the right guidance and treatment approach, effective options are still available. Care focuses on helping you understand your condition and explore the most suitable path toward parenthood.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Premature Ovarian Failure?',
        paragraphs: [
          'Premature ovarian failure (also known as primary ovarian insufficiency) occurs when the ovaries stop functioning normally before the age of 40. This leads to reduced egg production and irregular or absent ovulation.',
          'The condition is evaluated using advanced diagnostic protocols, ensuring accurate assessment and personalised care.',
        ],
      },
      {
        type: 'image',
        src: '/images/conditions/premature-ovarian-failure-pof-treatment-in-mumbai.webp',
        alt: 'Premature ovarian failure treatment and fertility care at Wonder IVF Mumbai',
      },
      {
        type: 'list',
        heading: 'Causes of Premature Ovarian Failure',
        intro: 'Premature ovarian failure can occur due to various factors, including:',
        items: [
          'Genetic conditions or chromosomal abnormalities',
          'Autoimmune disorders affecting ovarian function',
          'Previous chemotherapy or radiation treatment',
          'Hormonal imbalances',
          'Unknown or idiopathic causes',
        ],
        note: 'Understanding the underlying cause helps guide treatment planning.',
      },
      {
        type: 'list',
        heading: 'Symptoms of Premature Ovarian Failure',
        intro: 'Symptoms may vary, but commonly include:',
        items: [
          'Irregular or missed periods',
          'Difficulty in conceiving',
          'Hot flashes and night sweats',
          'Vaginal dryness',
          'Mood changes or fatigue',
        ],
        note: 'Early diagnosis can improve treatment outcomes.',
      },
      {
        type: 'list',
        heading: 'How Is POF Diagnosed?',
        intro: 'Premature ovarian failure may be diagnosed through:',
        items: [
          'AMH test (Anti-Müllerian Hormone) — indicates ovarian reserve',
          'FSH and LH levels — elevated levels suggest reduced ovarian function',
          'Ultrasound (AFC) — assesses follicle count in the ovaries',
          'Clinical evaluation of symptoms and medical history',
        ],
        note: 'This comprehensive approach supports an accurate diagnosis.',
      },
      {
        type: 'list',
        heading: 'Impact on Fertility',
        intro: 'Premature ovarian failure affects fertility by:',
        items: [
          'Reducing egg quantity and quality',
          'Causing irregular or absent ovulation',
          'Lowering chances of natural conception',
        ],
        note: 'However, with the right treatment approach, many patients are still able to achieve successful outcomes.',
      },
      {
        type: 'list',
        heading: 'Treatment Options for Premature Ovarian Failure',
        intro: 'Treatment is tailored based on your condition and fertility goals:',
        items: [
          'Hormonal therapy to manage symptoms and support reproductive health',
          'Customised IVF protocols for the ovarian response available',
          'Donor egg IVF in selected cases',
          'Fertility counseling and long-term planning',
        ],
        note: 'The plan is built around your individual diagnosis and goals.',
      },
      {
        type: 'list',
        heading: 'Benefits of Early Intervention',
        items: [
          'Better understanding of fertility options',
          'Improved treatment planning',
          'Higher chances of success with the right approach',
          'Emotional support and clarity',
          'Access to advanced fertility solutions',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for POF Care?',
        items: [
          'Accurate diagnosis and evaluation',
          'Personalised treatment strategies',
          'Advanced fertility techniques',
          'Ethical and transparent approach',
          'Care aligned with leading fertility treatment standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Hope',
        text: 'Premature ovarian failure does not mean the end of your journey — it means finding the right approach forward. Wonder IVF guides you with clarity, care, and expertise as you take confident steps ahead.',
      },
    ],
  },
  {
    slug: 'recurrent-ivf-failure',
    path: '/recurrent-ivf-failure/',
    group: 'female',
    title: 'Recurrent IVF Failure',
    lede: 'Understanding the Challenges, Finding the Right Path Forward',
    metaTitle: 'Recurrent IVF Failure Treatment | Reasons for IVF Failure in India',
    metaDescription:
      'Understand the reasons for IVF failure and explore recurrent IVF failure treatment with personalised evaluation to help identify factors affecting IVF success.',
    image: '/images/conditions/repeated-ivf-failure-treatment-mumbai.webp',
    imageAlt: 'Repeated IVF failure treatment and fertility support in Mumbai',
    blocks: [
      {
        type: 'prose',
        paragraphs: [
          'It can be emotionally and physically challenging when IVF cycles do not lead to a successful pregnancy. Recurrent IVF failure refers to repeated unsuccessful IVF attempts despite good-quality embryos and proper treatment protocols.',
          'With deeper evaluation and a personalised approach, many couples can still achieve success. Care focuses on identifying underlying causes and optimising every step of your next cycle.',
        ],
      },
      {
        type: 'prose',
        heading: 'What Is Recurrent IVF Failure?',
        paragraphs: [
          'Recurrent IVF failure is generally defined as failure to achieve pregnancy after multiple IVF cycles, especially when good-quality embryos have been transferred.',
          'Evaluation can go beyond routine testing to identify hidden factors that may affect implantation and pregnancy.',
        ],
      },
      {
        type: 'list',
        heading: 'Possible Causes of Recurrent IVF Failure',
        intro: 'There can be multiple reasons why IVF cycles may not succeed, including:',
        items: [
          'Poor embryo quality or genetic abnormalities',
          'Implantation failure due to uterine factors',
          'Hormonal imbalances',
          'Endometrial receptivity issues',
          'Sperm DNA damage',
          'Immune or inflammatory conditions',
          'Lifestyle and metabolic factors',
        ],
        note: 'Understanding the root cause is key to improving outcomes.',
      },
      {
        type: 'list',
        heading: 'Advanced Evaluation After IVF Failure',
        intro: 'A detailed reassessment may be carried out to identify contributing factors:',
        items: [
          'Embryo quality and genetic testing (PGT)',
          'Uterine evaluation (hysteroscopy, ultrasound)',
          'Hormonal and metabolic assessment',
          'Sperm DNA fragmentation testing',
          'Endometrial receptivity analysis, if required',
        ],
        note: 'This comprehensive approach helps refine your treatment plan.',
      },
      {
        type: 'list',
        heading: 'Treatment Strategies for Better Outcomes',
        intro: 'Based on diagnosis, a personalised plan is created to improve the chances of success in the next cycle:',
        items: [
          'Optimized IVF protocols tailored to your response',
          'Use of ICSI for better fertilization outcomes',
          'Advanced embryo selection techniques',
          'Laser assisted hatching (LAH) in selected cases',
          'Improved embryo transfer strategies',
          'Lifestyle and medical optimization',
        ],
        note: 'Every step is carefully planned to support the next cycle.',
      },
      {
        type: 'list',
        heading: 'How Wonder IVF Improves Your Chances',
        intro: 'Care focuses on refining every stage of the IVF process:',
        items: [
          'Better embryo selection and lab practices',
          'Personalised treatment protocols',
          'Precise timing of embryo transfer',
          'Improved uterine environment for implantation',
        ],
        note: 'This approach may increase the chances of success in subsequent cycles.',
      },
      {
        type: 'list',
        heading: 'Benefits of a Personalized Approach',
        items: [
          'Identifies hidden causes of failure',
          'Improves implantation success rates',
          'Reduces repeated unsuccessful cycles',
          'Provides clarity and direction',
          'Enhances confidence in future treatment',
        ],
      },
      {
        type: 'list',
        heading: 'Why Choose Wonder IVF for Recurrent IVF Failure?',
        items: [
          'Detailed reassessment and advanced diagnostics',
          'Customised treatment strategies',
          'Integration of advanced IVF technologies',
          'Ethical and transparent care',
          'Alignment with leading fertility treatment standards',
        ],
      },
      {
        type: 'note',
        heading: 'Move Forward with Renewed Confidence',
        text: 'Recurrent IVF failure does not mean the end of your journey — it means finding a better approach. Wonder IVF guides you with expertise, care, and clarity as you take the next step with confidence.',
      },
    ],
  },
];
